version: '3'
networks:
  default:
    driver: bridge
  portland_synonyms:
    driver: bridge
volumes:
  libpostaldata:
    driver: local
services:
  libpostal_baseimage:
    image: pelias/libpostal_baseimage
    container_name: pelias_libpostal_baseimage
  libpostal:
    image: pelias/go-whosonfirst-libpostal
    container_name: pelias_libpostal
    restart: always
    ports: [ "8080:8080" ]
  schema:
    image: pelias/schema:portland-synonyms
    container_name: pelias_schema
    networks:
      - portland_synonyms
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "./synonyms/custom_street.txt:/code/pelias/schema/synonyms/custom_street.txt"
  api_portland_synonyms:
    image: pelias/api:master
    container_name: pelias_api_portland_synonyms
    restart: always
    environment: [ "PORT=4010" ]
    ports: [ "4010:4010" ]
    networks:
      - portland_synonyms
      - default
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "libpostaldata:/usr/share/libpostal"
  placeholder:
    image: pelias/placeholder:master
    container_name: pelias_placeholder
    restart: always
    environment: [ "PORT=4100" ]
    ports: [ "4100:4100" ]
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
  whosonfirst:
    image: pelias/whosonfirst:master
    container_name: pelias_whosonfirst
    networks:
      - portland_synonyms
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
  openstreetmap:
    image: pelias/openstreetmap:master
    container_name: pelias_openstreetmap
    networks:
      - portland_synonyms
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
  openaddresses:
    image: pelias/openaddresses:master
    container_name: pelias_openaddresses
    networks:
      - portland_synonyms
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
  polylines:
    image: pelias/polylines:master
    container_name: pelias_polylines
    networks:
      - portland_synonyms
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
  interpolation:
    depends_on: [ "libpostal_baseimage" ]
    image: pelias/interpolation:master
    container_name: pelias_interpolation
    restart: always
    environment: [ "PORT=4300" ]
    ports: [ "4300:4300" ]
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "libpostaldata:/usr/share/libpostal"
      - "${DATA_DIR}:/data"
  pip:
    image: pelias/pip-service:master
    container_name: pelias_pip-service
    restart: always
    environment: [ "PORT=4200" ]
    ports: [ "4200:4200" ]
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
  document-service:
    image: pelias/document-service:master
    container_name: pelias_document-service
    restart: always
    ports: [ "5000:5000" ]
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
  elasticsearch_portland_synonyms:
    image: pelias/elasticsearch
    container_name: pelias_elasticsearch_portland_synonyms
    restart: always
    networks:
      portland_synonyms:
        aliases:
          - elasticsearch
    volumes:
      - "./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro"
      - "${DATA_DIR}/elasticsearch_portland_synonyms:/usr/share/elasticsearch/data"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    environment:
      ES_HEAP_SIZE: 20g
    cap_add: [ "IPC_LOCK" ]
    security_opt:
      - seccomp=unconfined
